/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as GenshinRouteImport } from './routes/genshin'
import { Route as ArknightsRouteImport } from './routes/arknights'
import { Route as IndexRouteImport } from './routes/index'

const GenshinRoute = GenshinRouteImport.update({
  id: '/genshin',
  path: '/genshin',
  getParentRoute: () => rootRouteImport,
} as any)
const ArknightsRoute = ArknightsRouteImport.update({
  id: '/arknights',
  path: '/arknights',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/arknights': typeof ArknightsRoute
  '/genshin': typeof GenshinRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/arknights': typeof ArknightsRoute
  '/genshin': typeof GenshinRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/arknights': typeof ArknightsRoute
  '/genshin': typeof GenshinRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/arknights' | '/genshin'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/arknights' | '/genshin'
  id: '__root__' | '/' | '/arknights' | '/genshin'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArknightsRoute: typeof ArknightsRoute
  GenshinRoute: typeof GenshinRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/genshin': {
      id: '/genshin'
      path: '/genshin'
      fullPath: '/genshin'
      preLoaderRoute: typeof GenshinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arknights': {
      id: '/arknights'
      path: '/arknights'
      fullPath: '/arknights'
      preLoaderRoute: typeof ArknightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArknightsRoute: ArknightsRoute,
  GenshinRoute: GenshinRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
